# Generated by Django 6.1 on 2026-08-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('inquiry_type', models.CharField(choices=[('general', 'General inquiry'), ('product', 'Product inquiry'), ('partnership', 'Partnership'), ('farmer_supplier', 'Farmer/supplier'), ('distribution', 'Distribution'), ('training', 'Training'), ('investment', 'Investment/support'), ('other', 'Other')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'contact inquiry',
                'verbose_name_plural': 'contact inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
